# Generated by Django 2.0.1 on 2018-03-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudboard', '0002_snippet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
