# Generated by Django 2.0.1 on 2018-03-20 02:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudboard', '0003_auto_20180320_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboard',
            name='snippet_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], max_length=10, size=None),
        ),
    ]
