# Generated by Django 2.0.1 on 2018-04-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudboard', '0005_remove_clipboard_snippet_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
