# Generated by Django 2.0.1 on 2018-04-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudboard', '0006_clipboard_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
