# Generated by Django 2.0.1 on 2018-04-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudboard', '0008_snippet_raw_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='file',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='raw_bin',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
