# Generated by Django 2.0.1 on 2018-04-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudboard', '0009_auto_20180412_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
