# Generated by Django 2.0.1 on 2018-04-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudboard', '0010_snippet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
